#!/usr/bin/env node
// Entity-graph validation report.
//
// Runs against the D1 database via wrangler and prints the counts an operator
// needs to confirm the entity graph built correctly:
//   - addresses / people_orgs / projects created
//   - permits assigned to projects + orphan permits
//   - top 20 addresses and contractors by permit count
//   - pages generated by type + sitemap URL counts
//
// Usage:
//   node scripts/entity_report.mjs            # remote D1 (default)
//   node scripts/entity_report.mjs --local    # local/dev D1
//   node scripts/entity_report.mjs --json     # machine-readable output
//
// Tip: build the graph first with
//   curl -X POST -H "X-Admin-Token: $ADMIN_API_TOKEN" https://buildingseattle.com/admin/build-graph

import { execFileSync } from "node:child_process";

const args = new Set(process.argv.slice(2));
const LOCAL = args.has("--local");
const AS_JSON = args.has("--json");
const DB = "buildingseattle";

function query(sql) {
  const cmd = ["wrangler", "d1", "execute", DB, LOCAL ? "--local" : "--remote", "--json", "--command", sql];
  try {
    const out = execFileSync("npx", cmd, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const parsed = JSON.parse(out);
    // wrangler returns an array of result objects; rows live under .results.
    const block = Array.isArray(parsed) ? parsed[0] : parsed;
    return block?.results || [];
  } catch (err) {
    const msg = err.stderr?.toString() || err.message;
    throw new Error(`Query failed (${sql.slice(0, 60)}...): ${msg}`);
  }
}

const scalar = (sql, key = "n") => Number(query(sql)[0]?.[key] || 0);

function main() {
  const counts = {
    addresses: scalar("SELECT COUNT(*) AS n FROM addresses"),
    people_orgs: scalar("SELECT COUNT(*) AS n FROM people_orgs"),
    projects: scalar("SELECT COUNT(*) AS n FROM projects"),
    neighborhoods: scalar("SELECT COUNT(*) AS n FROM neighborhoods"),
    permits: scalar("SELECT COUNT(*) AS n FROM permits"),
    permits_assigned_to_projects: scalar("SELECT COUNT(*) AS n FROM permits WHERE project_id IS NOT NULL"),
    orphan_permits: scalar("SELECT COUNT(*) AS n FROM permits WHERE project_id IS NULL"),
  };

  const topAddresses = query(
    `SELECT a.display_address, a.slug, COUNT(p.id) AS permits, COALESCE(SUM(p.value),0) AS total_value
     FROM addresses a JOIN permits p ON p.address_id = a.id
     GROUP BY a.id ORDER BY permits DESC, total_value DESC LIMIT 20`,
  );

  const topContractors = query(
    `SELECT o.name, o.slug, COUNT(pp.permit_id) AS permits
     FROM people_orgs o JOIN permit_participants pp ON pp.people_org_id = o.id AND pp.role = 'contractor'
     GROUP BY o.id ORDER BY permits DESC LIMIT 20`,
  );

  const pagesByType = {
    address: counts.addresses,
    project: counts.projects,
    contractor: scalar(
      `SELECT COUNT(DISTINCT o.id) AS n FROM people_orgs o
       WHERE EXISTS (SELECT 1 FROM permit_participants pp WHERE pp.people_org_id = o.id)`,
    ),
    neighborhood: counts.neighborhoods,
    permit: counts.permits,
  };

  // Sitemap = 2 static + permits + addresses + projects + linked orgs + neighborhoods.
  const sitemapUrlCount =
    2 + counts.permits + counts.addresses + counts.projects + pagesByType.contractor + counts.neighborhoods;

  if (AS_JSON) {
    console.log(JSON.stringify({ counts, pagesByType, sitemapUrlCount, topAddresses, topContractors }, null, 2));
    return;
  }

  const line = (label, value) => console.log(`  ${label.padEnd(34)} ${value}`);
  console.log("\n=== Building Seattle — Entity Graph Report ===\n");
  console.log("Counts");
  line("addresses created", counts.addresses);
  line("people_orgs created", counts.people_orgs);
  line("projects created", counts.projects);
  line("neighborhoods created", counts.neighborhoods);
  line("permits total", counts.permits);
  line("permits assigned to projects", counts.permits_assigned_to_projects);
  line("orphan permits (no project)", counts.orphan_permits);

  console.log("\nPages by type");
  for (const [type, n] of Object.entries(pagesByType)) line(type, n);
  line("sitemap URL count", sitemapUrlCount);

  console.log("\nTop 20 addresses by permit count");
  topAddresses.forEach((a, i) =>
    console.log(`  ${String(i + 1).padStart(2)}. ${a.display_address} — ${a.permits} permits, $${Number(a.total_value).toLocaleString()}`),
  );

  console.log("\nTop 20 contractors by permit count");
  topContractors.forEach((c, i) => console.log(`  ${String(i + 1).padStart(2)}. ${c.name} — ${c.permits} permits`));
  console.log("");
}

try {
  main();
} catch (err) {
  console.error("Report failed:", err.message);
  console.error("Make sure wrangler is authenticated and the entity graph tables exist (run migration_entity_graph.sql).");
  process.exit(1);
}
